name: CI_Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
                
    - name: Install requirements
      run: pip3 install -r app/requirements.txt
       
    - name: Execute tests
      run: python3 test.py
            
