name: CI_Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    
    - name: Install python
      run: |
            apt-get update
            apt-get upgrade -y
            apt-get install python3 -y
            apt-get install pip3 -y
            
    - name: Install requirements
      run: pip3 install -r app/requirements.txt
       
    - name: Execute tests
      run: python3 test.py
            
